// AUTO-GENERATED by scripts/build-changelog.mjs from changes/*.md — DO NOT EDIT.
// Add a changes/<slug>.md file instead (see changes/README.md).
import type { ChangelogEntry } from "./changelog-types";

export const GENERATED_CHANGELOG: ChangelogEntry[] = [
  {
    "version": "0.1.463",
    "date": "2026-09-18",
    "headline": "Save a theme to a file and open it anywhere",
    "highlights": [
      "Export any theme to a file you can back up, email, or send to another church. Import it from the Themes area and it comes in as a brand-new theme — your existing themes are never overwritten.",
      "Fonts, colours, text placement, transitions and scripture settings all come across exactly as they were. Import it back into your own church and you get the pictures too.",
      "Pictures and videos belong to the church that uploaded them, so they can't travel to a different church. If one can't come with the theme, PresentFlow now tells you which one and reminds you to pick your own background — instead of leaving a broken picture on screen."
    ]
  },
  {
    "version": "0.1.462",
    "date": "2026-09-18",
    "headline": "The new Layers panel, theme editor and slide menus now fit small Windows laptops",
    "highlights": [
      "Opening Layers now scrolls the panel into view. On smaller screens it used to open below the edge of the right panel, so it looked like nothing had happened.",
      "In the slide editor, the zoom buttons and the Fit button no longer slide off the right-hand edge on a small screen. The X, Y, W and H numbers shorten instead.",
      "The projection zone settings under the slide editor now stack into one column when the editor is narrow, so the Margins boxes and the Center button no longer sit on top of each other.",
      "Right-click menus on a slide now scroll instead of running off the bottom of a short screen, so you can always reach Delete Slide.",
      "On small Windows screens the card-size slider in the slide header now hides, so the Grid, List and Text view buttons are never cut off."
    ]
  },
  {
    "version": "0.1.460",
    "date": "2026-09-18",
    "headline": "Themes now live in one place — the Themes menu on the top bar",
    "highlights": [
      "The old Themes window has been put away. Everything it did is now in the Themes menu on the top bar, where you already apply themes.",
      "Import from ProPresenter moved there too — it's the upload button at the top of the Themes menu.",
      "You can still choose a default look for Songs and for Bible verses: it's now at the bottom of the Themes menu.",
      "Nothing changed about your themes themselves. Settings → Themes & Look still opens the same menu, so old shortcuts keep working."
    ]
  },
  {
    "version": "0.1.459",
    "date": "2026-09-17",
    "headline": "Fonts you pick now really show on the projector",
    "highlights": [
      "Every font in the font menus now really loads, so it shows its true look on the projector, the stage screen and the livestream — before, seven of them quietly fell back to a plain system font. Because they now load, some slides and themes may look different from last Sunday, so it is worth a quick look before the service.",
      "Bold, light and italic now look bold, light and italic. Each font only offers the weights it really has — Georgia, Arial and Times New Roman now offer regular and bold only, because that is all your computer actually has.",
      "The font menu is now split into \"PresentFlow fonts\", which look the same on every computer in the church, and \"System fonts\", which can look different from machine to machine. Fonts that cannot show Yoruba or Igbo letters say so in the list.",
      "The fonts are built into PresentFlow, so they keep working with no internet once they have loaded, on Windows as well as Mac.",
      "Text is measured after its font has loaded, so a slide no longer resizes a moment after it goes live — and lyrics still never get cut off.",
      "Your saved themes and slides are untouched: whatever font you picked before is still picked, and a font we do not recognise is offered as \"Keep current\" instead of being swapped out."
    ]
  },
  {
    "version": "0.1.458",
    "date": "2026-09-18",
    "headline": "The editor's properties panel is now split into Shape, Text and Build",
    "highlights": [
      "Selecting something in the slide or theme editor now gives you Shape, Text and Build tabs instead of one long list you had to scroll.",
      "Shape holds position, size, flip, rotation, see-through and colours. Text holds the wording, font and spacing. Build holds the entrance animation.",
      "Every setting you had before is still there and still does the same thing — nothing was removed or renamed.",
      "Tabs that would have nothing in them are not shown. A shape or a picture has no Text tab, because there is no wording to change."
    ]
  },
  {
    "version": "0.1.457",
    "date": "2026-09-18",
    "headline": "Rulers, a grid and a transparency checker for the slide and theme editor",
    "highlights": [
      "A new View button in the editor's bottom bar turns on rulers along the top and left edges, a grid over the slide, and a checkerboard that shows where a slide has no background of its own.",
      "The rulers show a marker that follows your pointer, so you can line things up by eye.",
      "Everything is off to start with and PresentFlow remembers what you switched on, on this computer.",
      "Snap guides — the lines that appear while you drag something into line — work exactly as before, and you can now switch them off from the same menu.",
      "On a short screen the rulers hide themselves so the slide stays big enough to work on."
    ]
  },
  {
    "version": "0.1.456",
    "date": "2026-09-18",
    "headline": "Adding a text box, shape, image or video to a slide is now one click above the canvas",
    "highlights": [
      "The slide and theme editor has a new Add bar across the top of the canvas — Text, Rectangle, Ellipse, Image and Video.",
      "You no longer have to open the Add tab on the right to put something on a slide. That tab still works exactly as before if you prefer it.",
      "On narrower Windows screens the bar shows icons only. Hover or focus a button to see its name."
    ]
  },
  {
    "version": "0.1.455",
    "date": "2026-09-18",
    "headline": "The slide and theme editor now shows exactly where things sit, and you can zoom in",
    "highlights": [
      "A new bar under the canvas shows the position and size of whatever you have selected, and it updates live as you drag.",
      "You can now zoom the canvas in and out, or snap back to Fit. Ctrl+0 (Cmd+0 on a Mac) fits the slide to the window.",
      "\"Lock size\" keeps a box in its shape — drag a corner or type a new width and the height follows, so a logo never gets squashed.",
      "New Flip Horizontal and Flip Vertical buttons mirror the selected box.",
      "Nothing about your existing slides or themes changed — they project exactly as before."
    ]
  },
  {
    "version": "0.1.454",
    "date": "2026-09-17",
    "headline": "Themes now come ready-made, keep their moving backgrounds smooth, and apply to many slides or a whole service at once",
    "highlights": [
      "Seven built-in themes (Default, Classic, Modern, Minimal, Church, Dark, Light) are in the Theme menu. Apply one straight away, or duplicate it and make it your own.",
      "A theme's pictures, shapes and videos now also show behind slides you designed yourself, unless the slide is a full-screen picture or video.",
      "A video in your theme keeps playing smoothly when you change slides instead of starting again.",
      "In a song, Cmd/Ctrl-click or Shift-click to select several slides, then use Theme to apply a theme to just those slides.",
      "Use \\\"Apply theme to all items…\\\" on a service to theme everything in it at once, with Undo.",
      "Bible items now have a Theme option too, plus \\\"Use for all Bible verses\\\".",
      "Removing or re-applying a theme on songs no longer leaves the old theme's background behind."
    ]
  },
  {
    "version": "0.1.453",
    "date": "2026-09-17",
    "headline": "The Layers panel now matches ProPresenter",
    "highlights": [
      "The Layers panel lists the same seven layers as the clear bar beside your live preview, in the same order - Audio, Messages, Props, Announcements, Slide, Media, Video Input.",
      "Each layer has one clear button, and Clear All is the same round X you already use on the clear bar. The old press-and-hold Clear All and the eye hide buttons are gone.",
      "\"Background\" is now called Media, \"Camera\" is now Video Input and the church logo now sits under Props, so the panel and the clear bar say the same thing.",
      "You can still change the background media, set the church logo, switch a slide between full screen and lower third, and re-send or jump to a slide from the same panel.",
      "Clearing Messages now also takes a countdown or timer off the screen, and Clear All really does clear everything, including timers.",
      "The clear keys (F1 to F7) now still work while a menu or picker is open, so you can clear without closing what you are looking at first.",
      "F5 no longer reloads the app mid-service.",
      "Clear All has a second shortcut that works on every keyboard - Ctrl+Shift+C on Windows, Command+Shift+C on Mac - because F1 is the brightness key on most Macs.",
      "The Props clear button now always works, even if your church has not set a logo. Audio is clearly marked as not available yet, instead of looking like a button that does nothing.",
      "In the old Layers panel, Clear All now stops the camera as well, so both Clear All buttons leave the app in the same state."
    ]
  },
  {
    "version": "0.1.451",
    "date": "2026-09-17",
    "headline": "One Settings window — Bible, CCLI and Automations moved out of the small gear at the bottom of the panel",
    "highlights": [
      "The small gear at the bottom-right of the operator panel is gone. There is now one Settings window, opened by the gear at the top next to the Present Flow logo.",
      "Your CCLI number, your API.Bible key and your licensed translations are now in Settings, under \"Bible & Detection\".",
      "Automations now have their own section in Settings. Creating, editing, test-running and deleting them all work exactly as before.",
      "Type \"ccli\" or \"automation\" into the Settings search box to jump straight to them.",
      "The rest of the bottom icon row is unchanged — Bible, Songs, Cross-references, Layers, Timers and Messages all stay where they were."
    ]
  },
  {
    "version": "0.1.450",
    "date": "2026-09-17",
    "headline": "Songs now open with your chosen song look, even on the first slide of a fresh session",
    "highlights": [
      "Sometimes the very first song you put up in a new session came out in the plain default look — white text, no background — until you clicked away to another item and back. That's fixed.",
      "If your church's themes are slow to load when the console opens, PresentFlow now keeps trying for a few seconds and applies your song look as soon as they arrive. The screen updates in place, with no re-cut or flash."
    ]
  },
  {
    "version": "0.1.449",
    "date": "2026-09-17",
    "headline": "Song backgrounds from your theme now show on the live screen, matching the slide previews",
    "highlights": [
      "If you picked a theme for songs, its background now shows on the live screen and projector, not just on the slide previews.",
      "When the same song is in your service more than once, the live screen uses the theme of the copy you actually clicked.",
      "Theme logos that had stopped loading after a while now load again."
    ]
  },
  {
    "version": "0.1.448",
    "date": "2026-09-17",
    "headline": "Your Scripture Style and default song and Bible themes are now shared across every computer in your church",
    "highlights": [
      "Set the Scripture Style (full screen or lower third, band colour, text size) once and every computer in your church uses it. Before, each computer kept its own.",
      "The default theme you pick for Songs and for Bible verses is now the same on every computer in your church.",
      "A change made on one computer shows up on the others within about a minute, without reloading or changing what is on the screen.",
      "Volunteers can still change the Scripture Style during a service. Changing the default song and Bible themes needs someone who can edit the library.",
      "Your existing style carries over automatically the first time you open PresentFlow. If two computers had different styles, the first one to open wins."
    ]
  },
  {
    "version": "0.1.447",
    "date": "2026-09-17",
    "headline": "Intel Macs now update automatically, and the Windows pro audio driver is more reliable",
    "highlights": [
      "Intel Macs now get PresentFlow updates automatically, like Apple Silicon Macs and Windows. If you're on an Intel Mac and stuck on an older version, install the latest Intel (x64) download once and it will keep itself up to date from then on.",
      "On Windows, the pro audio driver for USB mixers and interfaces stays switched on reliably instead of occasionally turning itself off at startup."
    ]
  },
  {
    "version": "0.1.446",
    "date": "2026-09-17",
    "headline": "Videos fill the screen like ProPresenter, plus a band tip",
    "highlights": [
      "Videos now fill the screen like ProPresenter. A smaller video (like 720p) grows to fit the screen instead of sitting small in the middle. It keeps its shape, with black bars if needed. Pick \"cover\" to fill and crop, or \"fill\" to stretch.",
      "A tip in lower-third settings lets you try the more visible band. It only shows if your band is still plain black, and nothing changes unless you tap \"Try it\" and save."
    ]
  },
  {
    "version": "0.1.445",
    "date": "2026-09-17",
    "headline": "Pictures and videos fill the screen, and the lower-third band is easier to see",
    "highlights": [
      "Pictures and videos now fill the whole screen, even when you use the lower-third layout. The lower-third band is just for words, like in ProPresenter. (changed in 0.1.445)",
      "The lower-third band is easier to see. If you haven't picked your own band colour, it is now a soft dark bar you can see on a black screen and over pictures. Your own band colour stays the same.",
      "Captions you set on a picture or video still show in the band, and are always easy to read.",
      "Small pictures are no longer blown up until they look blurry."
    ]
  },
  {
    "version": "0.1.444",
    "date": "2026-09-17",
    "headline": "Everything you design in a theme now shows on the projector, your songs and the theme previews",
    "highlights": [
      "Images, shapes, extra text and slide backgrounds you add to a theme now appear behind the words on every slide using that theme, on the projector, livestream and NDI. It works like ProPresenter.",
      "The Themes cards now show a real preview of each theme, including its images and text boxes.",
      "Song and slide thumbnails in the operator show the theme that item will use. A theme applied to a whole song is used when that song goes live.",
      "If you moved or resized the lyrics box in a theme, songs appear in that box and the words shrink to fit so nothing spills out. The same box is used for other text slides, such as announcements.",
      "Scripture follows your theme's verse and reference boxes and its reference and translation options. The Bible preview cards now match what the projector shows.",
      "A saved Scripture Style on this computer still wins. The theme editor now tells you when that happens and lets you clear it.",
      "A transition set in a theme is used when its slides go live. Bible card clicks still cut straight in, and AI and voice verse changes still use the quick fade.",
      "Theme changes take effect straight away without restarting. The stage display stays full screen."
    ]
  },
  {
    "version": "0.1.443",
    "date": "2026-09-17",
    "headline": "New \"Audio interface & Blackmagic\" panel in Audio",
    "highlights": [
      "Audio now has an \"Audio interface & Blackmagic\" panel next to NDI network audio. It finds your USB mixer or interface (X32, XR18, SQ, WING, Focusrite and more) and Blackmagic inputs, and shows how many channels each has.",
      "Click a device to use it. On Windows, PresentFlow switches on the pro audio driver for you and picks the version that shows every channel.",
      "It rescans when you plug a device in or out, and there's a Rescan button. \"Stop interface\" goes back to your computer's default input.",
      "If the pro audio driver ever has a problem on a computer, PresentFlow now falls back to standard capture instead of closing."
    ]
  },
  {
    "version": "0.1.442",
    "date": "2026-09-17",
    "headline": "PowerPoint imports are faster and more reliable",
    "highlights": [
      "Drop a PowerPoint (or PDF) onto the Media Bin and it starts importing by itself — no extra Preview or Import clicks. (Adding files anywhere else still lets you check them first.)",
      "You can now see what's happening — uploading the deck, converting it (with a timer), then preparing and uploading each slide.",
      "Big, photo-heavy presentations now import properly instead of failing partway through.",
      "Press Cancel import to stop at any point — cancelled files are shown as cancelled, not as errors.",
      "Broken, password-protected, or non-PowerPoint files now show a clear message telling you what to do, and files over 150 MB are turned away before uploading."
    ]
  },
  {
    "version": "0.1.441",
    "date": "2026-09-17",
    "headline": "Clicking a picture in the Media Bin puts it on the screen again",
    "highlights": [
      "Click a picture or video in the Media Bin or the Media library and it goes straight to the screen, just like before.",
      "A click no longer changes the background behind all your slides. To do that, use the Bg button on the picture (or right-click → Set as background)."
    ]
  },
  {
    "version": "0.1.440",
    "date": "2026-09-16",
    "headline": "Better sound from USB mixers, audio interfaces and Blackmagic devices",
    "highlights": [
      "New option in Audio → \"Separate channels from my mixer (USB)\". Turn it on for a USB mixer or interface (X32, XR18, SQ, Focusrite, ATEM Mini) so each channel reaches PresentFlow on its own instead of being squashed together. It turns on automatically for recognised mixers and interfaces (ordinary microphones keep standard processing), and you can switch it off per device.",
      "Desktop app, new \"Pro audio driver\" (on by default, switch it off in Audio if needed): PresentFlow reads every input channel of your interface, including over ASIO on Windows, and shows the real channel count so you can pick the pastor's mic channel.",
      "Desktop app, Blackmagic UltraStudio and DeckLink devices can send their SDI/HDMI audio to PresentFlow's AI listening. You need Blackmagic Desktop Video 14.3 or newer installed.",
      "If a USB interface is unplugged during a service, PresentFlow now tries to reconnect it automatically."
    ]
  },
  {
    "version": "0.1.439",
    "date": "2026-09-17",
    "headline": "Edit a theme the same way you edit a slide",
    "highlights": [
      "In the Themes popover, the pencil (or right-click → Edit…) now opens the full-screen slide editor on that theme.",
      "A theme can have up to 12 slides. Choose what each text box shows (Lyrics, Verse or Reference) under \"This text box shows\" in the Design tab. Text box positions and these choices take effect on the projector in the next update.",
      "The new Theme tab holds the fonts, the background (colour, gradient with angle, image or video, dim, animation), the logo, scripture options and the transition. The canvas previews gradient and video backgrounds.",
      "Show only puts a theme slide in Preview. It never goes live.",
      "After you save, PresentFlow asks whether to restyle the songs that use the theme. Their lyrics are kept. If some songs can't be updated, you can press Retry.",
      "The sliders button still opens the old theme screen for now."
    ]
  },
  {
    "version": "0.1.438",
    "date": "2026-09-17",
    "headline": "The Windows app can now take audio from OBS over NDI and send your slides out over NDI",
    "highlights": [
      "In the Windows app, the Audio panel lists NDI network audio: pick your OBS (DistroAV) source and the AI listens to the service over the network, no USB cable from the mixer needed.",
      "If OBS closes, PresentFlow shows that the NDI feed was lost and carries on when OBS comes back.",
      "The Windows app appears as \"PresentFlow - NDI 1\", so OBS and other NDI tools can pick up your slides.",
      "Download the latest Windows app from your dashboard to get this. Windows apps already installed update on their own."
    ]
  },
  {
    "version": "0.1.437",
    "date": "2026-09-17",
    "headline": "New Themes popover, like ProPresenter",
    "highlights": [
      "Click Themes in the top bar to see your recent themes and all your themes as thumbnails. A blue dot shows the one in use.",
      "Click a theme to apply it. Right-click to rename, duplicate or delete.",
      "Press + to make a new theme — name it and choose a theme to start from.",
      "The pencil opens the full theme editor."
    ]
  },
  {
    "version": "0.1.436",
    "date": "2026-09-16",
    "headline": "Bigger videos and iPhone photos in the Media Bin",
    "highlights": [
      "Videos up to 5 GB now upload. Big files are sent in pieces behind the scenes, with the same progress ring — and cancelling really stops the upload. While something is live on screen, big uploads slow down on purpose so they don't disturb your service.",
      "iPhone photos (HEIC) just work — they're turned into normal JPG pictures on your computer before uploading.",
      "Audio in the Media Bin (MP3, WAV, M4A, AAC) is coming soon. Until it's switched on, dropping an audio file shows a short \"coming soon\" message instead of a failed upload.",
      "Uploads are checked more carefully: a file that isn't really a picture or video is turned away with a clear message, while a photo that was simply renamed (say a PNG saved as .jpg) still goes through."
    ]
  },
  {
    "version": "0.1.435",
    "date": "2026-09-16",
    "headline": "Editing images works again",
    "highlights": [
      "The Edit image window now always opens on top and every button responds, whether you open it from the Media Bin or the Media library. Press Esc to close it, and your keyboard shortcuts won't change the screen behind it while it's open.",
      "\"Auto-fill screen with logo\" and \"Remove flat background (beta)\" no longer leave Save and Save & Show greyed out.",
      "Drag the small orange squares on the corners to crop or resize the picture — they work again, even when the picture fills the whole screen, and your crop is kept after you press Save.",
      "In Logo on background, the logo keeps exactly the size and shape you set, and the Size slider moves with it.",
      "Clicking an edited picture in the Media Bin now shows it the way you framed it.",
      "If you cleared the words off the screen (T key), showing an edited picture now brings the screen back.",
      "Removing a flat background saves the result as a new picture in your Media library; the original picture is left as it was."
    ]
  },
  {
    "version": "0.1.433",
    "date": "2026-09-16",
    "headline": "Clear Messages now clears timers too",
    "highlights": [
      "The Messages clear button (and Clear All) now also takes timers off the screen."
    ]
  },
  {
    "version": "0.1.432",
    "date": "2026-09-16",
    "headline": "Drag files straight into the Media Bin",
    "highlights": [
      "Drag images and videos from Finder or File Explorer onto the Media Bin — each one appears right away with a progress ring and turns into a normal tile when it's done.",
      "Drop a PowerPoint or PDF and the import wizard opens with it ready, turning each slide into an image.",
      "Dragging files over a closed Media Bin opens it for you. You can drop whole folders too.",
      "If an upload fails you get Retry on the tile (and \"Retry all\" for several); if the internet drops, uploads wait and carry on when you're back online.",
      "Audio files and iPhone HEIC photos show a clear message for now instead of silently doing nothing.",
      "Dropping a file in the wrong place no longer opens it in another app."
    ]
  },
  {
    "version": "0.1.431",
    "date": "2026-09-16",
    "headline": "Layers now work like ProPresenter",
    "highlights": [
      "The clear buttons beside the preview now match ProPresenter — Messages, Props, Announcements, Slide, Media and Video Input (Audio is coming soon). Each one clears only its own layer.",
      "Full layer controls (show/hide each layer) are still under the Layers icon on the right.",
      "The white ✕ clears everything. The column turns red while something is live, and each live layer is highlighted.",
      "(Changed in 0.1.441: clicking an image or video in the Media Bin now puts it on the screen. Use the Bg button to put it behind your words.)",
      "Keyboard: F1 clears all, F2 slide, F3 media, F4 props, F6 messages, F7 announcements. On a Mac, hold Fn — or turn on \"Use F1, F2, etc. keys as standard function keys\" in Keyboard settings.",
      "With a camera live, media now shows over the camera and under the words, like ProPresenter. Press Clear Media (F3) to see the camera again."
    ]
  },
  {
    "version": "0.1.430",
    "date": "2026-09-16",
    "headline": "Songs, media, imports and your team now open inside the desktop app",
    "highlights": [
      "In Settings, Song library and song imports now open the Songs browser in the app, not your web browser.",
      "Media library opens the Media browser in the app.",
      "Church admins can invite people, change roles and remove members right in Settings, under Team & Church."
    ]
  },
  {
    "version": "0.1.429",
    "date": "2026-09-16",
    "headline": "Only people who run services can change the default theme",
    "highlights": [
      "Applying a theme as the church default now needs a role that can run services (admin, operator or volunteer).",
      "Pastor and viewer accounts can still see themes but can no longer change the default."
    ]
  },
  {
    "version": "0.1.428",
    "date": "2026-09-16",
    "headline": "Clear Messages now clears straight away",
    "highlights": [
      "Pressing Clear Messages removes every message from the projector and livestream immediately.",
      "Before, some messages could stay on screen for up to 5 seconds after you cleared them."
    ]
  },
  {
    "version": "0.1.427",
    "date": "2026-09-16",
    "headline": "PresentFlow fits smaller Windows laptops, with Windows keyboard labels",
    "highlights": [
      "On smaller Windows laptop screens, the live panel on the right gets a little narrower so your slides keep more room.",
      "On very small Windows screens, the search box and the Songs, Bible, Media and Themes buttons show as icons, so the settings button never falls off the edge.",
      "If you snap the Windows app to half the screen, the left panel shrinks to fit, and goes back to your chosen width on a bigger window.",
      "Windows now shows the right keys in hints and tooltips, for example Ctrl+Z to undo, Ctrl+Enter to save a quick edit, and Shift-click.",
      "On Windows, microphone audio is no longer boosted by default when you haven't set a boost. This stops it stacking with Windows' own boost and crackling. Settings › Audio has a tip for setting your Windows mic level. Any boost you've already chosen is kept."
    ]
  },
  {
    "version": "0.1.426",
    "date": "2026-09-16",
    "headline": "PresentFlow fits and feels smoother on Windows",
    "highlights": [
      "On Windows, the top bar no longer pushes the settings button off the edge of the screen.",
      "The red AUDIO warning no longer covers the buttons at the top right, so you can still click them.",
      "On narrower Windows screens, the Edit slide, Add slide and Tidy buttons show as icons instead of spilling under the live panel. Hover to see the name.",
      "The operator screen is lighter to run on Windows, and buttons stay still when you click them, so clicks land reliably.",
      "Windows shows \"Ctrl K\" for search instead of the Mac key.",
      "With the latest Windows desktop app, the window opens sized to your screen without the File/Edit/View menu bar, and PresentFlow stops turning your Windows microphone volume up."
    ]
  },
  {
    "version": "0.1.425",
    "date": "2026-09-16",
    "headline": "More settings now work right inside the desktop app",
    "highlights": [
      "Turn Layers on or off in Settings, under Screens & Outputs (church admins only).",
      "Your Bible translation, detection and auto-approve settings, and how long transcripts are kept, can now be changed right in the Settings window.",
      "Setting up your screens now opens the Screens panel in the app instead of your web browser.",
      "Signing out of all devices now works from Settings without leaving the app first."
    ]
  },
  {
    "version": "0.1.424",
    "date": "2026-09-16",
    "headline": "Your first verse goes live on the projector",
    "highlights": [
      "At the end of setup, say \"Let's turn to John chapter three, verse sixteen\" and Sarah puts it straight onto your live screen while the spotlight is on it.",
      "Sarah now looks things up on the web for questions she doesn't already know, using official sound-desk and streaming docs, and shows you where the answer came from.",
      "She tells you when your sound is coming in too quiet for her to follow the words.",
      "One step shorter, because she works out whether you're on a Mac or Windows herself.",
      "The level bar no longer says \"Too quiet\" right after your voice check passes."
    ]
  },
  {
    "version": "0.1.423",
    "date": "2026-09-16",
    "headline": "Lyrics and verses no longer get cut off on the projector or stage screen",
    "highlights": [
      "Fixed a bug where some slides lost their last line on the main projector and stage screen, while the NDI feed showed them in full. Every slide now fits the screen on every output.",
      "It could happen to short slides as well as long ones - it depended on which slide was showing while the lyric font finished loading. That no longer matters.",
      "Lyrics shown over your camera in lower-third mode now fit inside the band instead of spilling out of it.",
      "Long Bible verses no longer run into the reference line at the bottom.",
      "The text size control now goes from 30% up to 250%, so you have more room to suit your projector and room.",
      "Making text bigger never pushes it off the screen - short lines grow, and a slide that already fills the screen stays fitted. Making it smaller has no limit."
    ]
  },
  {
    "version": "0.1.422",
    "date": "2026-09-16",
    "headline": "Layers is now on for every church",
    "highlights": [
      "The strip on the right of the operator screen is now on for everyone, so you can hide the words, background, camera or logo one at a time.",
      "Church admins can turn Layers off in Settings if they don't want it."
    ]
  },
  {
    "version": "0.1.421",
    "date": "2026-09-16",
    "headline": "Sarah now shows you around the real app",
    "highlights": [
      "When it's time to pick your input, Sarah lights up the real Audio panel and coaches you through it, so you learn where it lives.",
      "For your first verse, the spotlight glides to the AI switch and then to the live preview, so you watch it land exactly where your congregation will see it.",
      "Sarah notices what's going on as you work, for example \"I can see your NDI source\", or \"no NDI sources, so check both computers are on the same wired network\".",
      "She spots common problems too, including a Blackmagic card with no picture, a silent Dante soundcard, an unplugged interface, sound coming in too loud, or being offline.",
      "The rest of the app stays fully usable while she's coaching."
    ]
  },
  {
    "version": "0.1.420",
    "date": "2026-09-16",
    "headline": "The X on your live preview now clears the whole screen",
    "highlights": [
      "Tap the X on the live preview to clear everything on the screen - words, Bible verses, background, camera and logo - in one tap.",
      "Send your next slide and everything comes back on its own.",
      "The T on the right-hand strip now hides the words only until the next slide is sent, whether you click a slide or a verse is put up for you. You never have to turn the words back on yourself.",
      "Hiding the background, camera or logo from the strip still keeps them hidden until you show them again."
    ]
  },
  {
    "version": "0.1.419",
    "date": "2026-09-16",
    "headline": "Sarah is now a spotlight, not a takeover",
    "highlights": [
      "Sarah opens in a smaller window you can see the app through, instead of covering the whole screen.",
      "No more emoji — clear icons instead.",
      "You only get a typing box when you actually need to type. Everything else is a simple choice.",
      "The settings gear now sits next to the PresentFlow logo in the top bar."
    ]
  },
  {
    "version": "0.1.418",
    "date": "2026-09-16",
    "headline": "Scenes - decide what each screen shows, and switch them all at once",
    "highlights": [
      "A new Scene row under your live preview lets you switch what every screen shows with one tap.",
      "Five scenes are ready to use - Worship, Teaching, Announcement, Offering and Pre-Service.",
      "Press Edit to see exactly what each scene shows, or press New scene to make your own.",
      "A scene only changes what each screen shows. It never changes what is playing, and anything you have already hidden yourself stays hidden.",
      "Choosing None puts every screen back to normal.",
      "Scenes are saved for your whole church, so any computer you sign in on has them. Deleting one removes it for everyone, so check before you delete."
    ]
  },
  {
    "version": "0.1.417",
    "date": "2026-09-16",
    "headline": "See any screen in your live preview, or all your screens at once",
    "highlights": [
      "Above the live preview you can now pick which screen it shows - Main, Stage, Livestream or NDI.",
      "Press All to see all four screens together inside the same box, updating live as you go - nothing to close, and the rest of the console stays usable.",
      "In the All view, click any screen to see that one full size.",
      "This is preview only. Picking a screen never changes what your projector, stage or stream shows.",
      "It always opens on Main, so you never walk into a service watching the wrong screen."
    ]
  },
  {
    "version": "0.1.416",
    "date": "2026-09-16",
    "headline": "Sarah now opens inside the app",
    "highlights": [
      "Run setup from Settings and Sarah opens over your operator screen — no more jumping out to a web page.",
      "She remembers what worked last time and offers to reuse it, or set up fresh.",
      "The voice check now passes as soon as she can hear you clearly, instead of making you keep talking.",
      "If you do not have the right gear, she tells you what to get and what to use in the meantime.",
      "After your sound is set up, Sarah asks you to say a verse out loud and shows the AI catching it — your first win in under five minutes.",
      "Simpler wording throughout the steps."
    ]
  },
  {
    "version": "0.1.415",
    "date": "2026-09-16",
    "headline": "Sarah walks you through connecting your sound",
    "highlights": [
      "Meet Sarah, your audio setup assistant. She asks what desk you use, shows the exact steps for your setup, then listens to check it actually works.",
      "She spots which channel your mixer is sending on, warns about hum, a too-quiet voice or distortion, and tells you how to fix each one.",
      "If one way of connecting does not work, she remembers and suggests the next one.",
      "Once it works, PresentFlow remembers that input and picks it automatically next time.",
      "Find her any time in Settings, under Audio Input.",
      "Settings now open from the gear in the top bar, or by pressing Cmd+comma (Ctrl+comma on Windows).",
      "Everything is in one place, grouped into Service, Output, Organisation and System.",
      "Search finds the setting you want, and tells you which section it is in.",
      "You can export this computer's settings to a file and import them on another machine.",
      "Attach actions to media, sermon, blank and logo slides, not just song slides.",
      "The action fires when you send that slide live, exactly as it does for songs.",
      "Scripture slides are not included yet, because their slide numbers change with translation."
    ]
  },
  {
    "version": "0.1.414",
    "date": "2026-09-16",
    "headline": "Search now finds Bible verses by their words, not just songs",
    "highlights": [
      "Press Cmd+K and type a phrase you remember — \"love is patient\", \"the Lord is my shepherd\" — and the verse comes up in a new Bible Verses group, with its reference and the words themselves.",
      "It still finds the verse when you remember the wording a little differently from the way your Bible puts it.",
      "The search box at the top of the web app does the same thing. Before, a remembered phrase only ever brought back songs.",
      "Songs stay on top: a song title you type — \"way maker\" — still comes back as the song, with verses underneath.",
      "Verses only appear when your words genuinely match a verse, so a typo or a stray phrase no longer fills the list with near-misses.",
      "Picking a verse opens it in the Bible panel ready to check. It does not send anything to the screen.",
      "Typing a reference like John 3:16 still goes straight to that verse, and a song line with numbers in it — \"bless the lord 10000 reasons\" — now shows both the song and the Bible results instead of hiding one."
    ]
  },
  {
    "version": "0.1.413",
    "date": "2026-09-16",
    "headline": "The right Mac download, every time",
    "highlights": [
      "Fixed: if the app can't tell which kind of Mac you have, it now asks instead of guessing — so an Intel Mac never gets a download it can't open.",
      "When it isn't sure, the update bar shows both choices, Apple Silicon and Intel Mac, with a reminder that the Apple menu → About This Mac tells you which one you have.",
      "When it can tell, nothing changes — one click still downloads the right build. Windows downloads are unchanged."
    ]
  },
  {
    "version": "0.1.412",
    "date": "2026-09-16",
    "headline": "The desktop app can update itself again",
    "highlights": [
      "Fixed: the desktop app was never checking for new versions, so churches had to download and re-install by hand to get anything new. It now checks again automatically.",
      "You are still asked before an update installs — nothing changes on your machine mid-service without you saying so.",
      "This takes effect from the next installer: install the new version once by hand, and updates after that come through on their own."
    ]
  },
  {
    "version": "0.1.411",
    "date": "2026-09-16",
    "headline": "The desktop app can reach everything it needs again",
    "highlights": [
      "Fixed: the offline copy of the Bible now downloads in the desktop app, so verses keep working when the internet drops.",
      "Fixed: the \"new version available — reload\" prompt appears in the desktop app again.",
      "Fixed: churches on a paid plan now get their Pro features and premium themes in the desktop app instead of being treated as a free plan.",
      "Fixed: importing a ProPresenter file from the desktop app no longer fails with a \"Parse failed\" error.",
      "Fixed: older pictures and videos in your media library now get their thumbnails filled in.",
      "Changed: starting a library import now needs an admin or operator account, matching every other library edit."
    ]
  },
  {
    "version": "0.1.410",
    "date": "2026-09-16",
    "headline": "A sound check no longer puts a Micah verse on screen",
    "highlights": [
      "Saying \"check mic two\" or \"testing mic one two\" during a sound check no longer suggests — or projects — a verse from Micah.",
      "Saying the book properly still works exactly as before: \"Micah chapter two\", \"Micah 1 verse 2\", \"turn to Micah 6\".",
      "Typing the short form in the reference box still works too: \"Mic 6:8\" and \"mic chapter 2\" both find Micah."
    ]
  },
  {
    "version": "0.1.409",
    "date": "2026-09-15",
    "headline": "Beta applications now reach the PresentFlow team inbox",
    "highlights": [
      "New beta applications from presentflow.org now appear in the PresentFlow Ops review queue.",
      "Your application confirmation is not delayed if the internal team inbox is temporarily unavailable."
    ]
  },
  {
    "version": "0.1.408",
    "date": "2026-09-15",
    "headline": "Fewer, more accurate Bible suggestions from preaching",
    "highlights": [
      "Bible suggestions from preaching now only appear when the preacher clearly quotes a verse (traditional wording works best), so you'll see fewer of them and they'll be right more often.",
      "They stay quiet while a song is on screen or when you're in Worship mode.",
      "When a passage is announced or on screen and read aloud, suggestions can follow along verse by verse.",
      "Suggestions never go on screen by themselves — click to load, Shift+click to send live."
    ]
  },
  {
    "version": "0.1.407",
    "date": "2026-09-15",
    "headline": "Transitions now live only in the left sidebar",
    "highlights": [
      "The transition picker and speed slider at the bottom of the screen have been removed.",
      "Choose your transition and its speed in the Transitions section of the left sidebar.",
      "Your saved transition still applies to the projector, stage and livestream screens, just as before."
    ]
  },
  {
    "version": "0.1.406",
    "date": "2026-09-15",
    "headline": "Find a song by any line of its lyrics",
    "highlights": [
      "In the Songs search, type a line you remember from a chorus, verse or bridge (even from slide 10) and the whole song comes up, with the matching line shown.",
      "Click a lyric match to open that song at the matching slide. It does not send anything to the screen.",
      "Press Cmd+K and the new Lyrics group finds songs the same way. Bible references like John 3:16 still go to the Bible.",
      "Small typos and half-finished words still find the song. Searching by title works exactly as before.",
      "Fixed: adding a Section header (or anything else) just after midnight could suddenly show an empty playlist. Nothing was deleted; the app was switching to a new day's service. It now keeps you on the service you are working on.",
      "If a newer service for today exists, you get a Switch to today's service button instead of being moved automatically.",
      "Clean up ad-hocs no longer deletes a service that still has items in it, or one that may be open right now.",
      "Fixed: when a song repeats its chorus and you add, delete or edit a slide while it is live, the next slide is now the one after the chorus on screen, not an earlier verse."
    ]
  },
  {
    "version": "0.1.405",
    "date": "2026-09-15",
    "headline": "Detection badges now show real numbers only",
    "highlights": [
      "Fixed: the red numbers on Bible detections, Songs and Cross-references now match exactly what you see when you open that panel.",
      "Fixed: when there is nothing detected, the number disappears instead of showing an old count.",
      "Pressing Clear on the AI chips bar now also clears those numbers back to zero. New detections still show up straight after.",
      "A Bible reference that does not exist (like John 99:99) no longer adds to the count.",
      "Fixed: after \"John 3:16\" then \"next verse\", the screen stays on verse 17 and no longer jumps back to 16.",
      "Fixed: polite commands like \"Amen church, can we go to next verse please\" now move to the next verse.",
      "Normal preaching such as \"we will see this in the next verse\" still does not move the screen.",
      "After Add slide, right-click the blank slide and choose Quick edit to type on it in the song's own font and colour, whatever theme or background is on.",
      "Cmd+Enter (Ctrl+Enter on Windows) saves. Send this slide live saves your text first, then puts it on screen.",
      "Pressing Esc or closing with unsaved typing now asks before throwing it away, and never clears what is on the projector."
    ]
  },
  {
    "version": "0.1.404",
    "date": "2026-09-14",
    "headline": "Signing in is more reliable — no more whole-church lockouts",
    "highlights": [
      "Fixed: if a password is typed wrong, the sign-in page now tells you clearly what happened and when you can try again, instead of a vague error.",
      "Fixed: several people signing in from the same church Wi-Fi no longer get locked out together because of one person's mistyped password."
    ]
  },
  {
    "version": "0.1.403",
    "date": "2026-09-14",
    "headline": "A full editor for your OBS live-stream words — with a real live preview",
    "highlights": [
      "Hardware → Screens → “Put lyrics on your live stream” is now a full editor for all three looks: Over your camera, Lower third, and Full projector look.",
      "The preview shows the slide that is ACTUALLY live right now, exactly as OBS will show it (or a sample song/verse when nothing is live).",
      "Over your camera (Full projector layout): text size, top/middle/bottom position, text colour, shadow or outline, and a dark background behind the words. Lower third: band style, height, position, text size, see-through, text colour and show/hide the verse reference. Full projector look: text size and darken background.",
      "Every tweak reaches OBS instantly while the app is open. Changing the LOOK itself only reaches links you create or copy from this new editor — links you already added to OBS keep their look, so nothing changes on your stream by surprise.",
      "Your own lower-third title (name / title lines) now shows on your OBS stream: in the band for the Lower third look, and on the Full projector look. On Over your camera it shows inside the band in the Lower third layout, or as a caption over the camera in the Full projector layout. It stays up until you send the next slide, or until you clear it.",
      "Your projector and operator screen are unchanged.",
      "Over your camera now has a Layout choice: Lower third (a see-through band over your camera — the default once you open the OBS editor on the computer running your service) or Full projector (the words across the whole camera picture, as before). In Lower third you can put the band Upper, Mid, Lower or a Custom position, and set its background, height, text size, see-through and text colour.",
      "In the camera Lower third layout, announcements, messages and timers are hidden so only the words sit over your camera. Switch the Layout to Full projector to show them."
    ]
  }
];
