// AUTO-GENERATED by scripts/build-changelog.mjs from changes/*.md — DO NOT EDIT.
// Add a changes/<slug>.md file instead (see changes/README.md).
import type { ChangelogEntry } from "./changelog-types";

export const GENERATED_CHANGELOG: ChangelogEntry[] = [
  {
    "version": "0.1.413",
    "date": "2026-09-16",
    "headline": "The right Mac download, every time",
    "highlights": [
      "Fixed: if the app can't tell which kind of Mac you have, it now asks instead of guessing — so an Intel Mac never gets a download it can't open.",
      "When it isn't sure, the update bar shows both choices, Apple Silicon and Intel Mac, with a reminder that the Apple menu → About This Mac tells you which one you have.",
      "When it can tell, nothing changes — one click still downloads the right build. Windows downloads are unchanged."
    ]
  },
  {
    "version": "0.1.412",
    "date": "2026-09-16",
    "headline": "The desktop app can update itself again",
    "highlights": [
      "Fixed: the desktop app was never checking for new versions, so churches had to download and re-install by hand to get anything new. It now checks again automatically.",
      "You are still asked before an update installs — nothing changes on your machine mid-service without you saying so.",
      "This takes effect from the next installer: install the new version once by hand, and updates after that come through on their own."
    ]
  },
  {
    "version": "0.1.411",
    "date": "2026-09-16",
    "headline": "The desktop app can reach everything it needs again",
    "highlights": [
      "Fixed: the offline copy of the Bible now downloads in the desktop app, so verses keep working when the internet drops.",
      "Fixed: the \"new version available — reload\" prompt appears in the desktop app again.",
      "Fixed: churches on a paid plan now get their Pro features and premium themes in the desktop app instead of being treated as a free plan.",
      "Fixed: importing a ProPresenter file from the desktop app no longer fails with a \"Parse failed\" error.",
      "Fixed: older pictures and videos in your media library now get their thumbnails filled in.",
      "Changed: starting a library import now needs an admin or operator account, matching every other library edit."
    ]
  },
  {
    "version": "0.1.409",
    "date": "2026-09-15",
    "headline": "Beta applications now reach the PresentFlow team inbox",
    "highlights": [
      "New beta applications from presentflow.org now appear in the PresentFlow Ops review queue.",
      "Your application confirmation is not delayed if the internal team inbox is temporarily unavailable."
    ]
  },
  {
    "version": "0.1.408",
    "date": "2026-09-15",
    "headline": "Fewer, more accurate Bible suggestions from preaching",
    "highlights": [
      "Bible suggestions from preaching now only appear when the preacher clearly quotes a verse (traditional wording works best), so you'll see fewer of them and they'll be right more often.",
      "They stay quiet while a song is on screen or when you're in Worship mode.",
      "When a passage is announced or on screen and read aloud, suggestions can follow along verse by verse.",
      "Suggestions never go on screen by themselves — click to load, Shift+click to send live."
    ]
  },
  {
    "version": "0.1.407",
    "date": "2026-09-15",
    "headline": "Transitions now live only in the left sidebar",
    "highlights": [
      "The transition picker and speed slider at the bottom of the screen have been removed.",
      "Choose your transition and its speed in the Transitions section of the left sidebar.",
      "Your saved transition still applies to the projector, stage and livestream screens, just as before."
    ]
  },
  {
    "version": "0.1.406",
    "date": "2026-09-15",
    "headline": "Find a song by any line of its lyrics",
    "highlights": [
      "In the Songs search, type a line you remember from a chorus, verse or bridge (even from slide 10) and the whole song comes up, with the matching line shown.",
      "Click a lyric match to open that song at the matching slide. It does not send anything to the screen.",
      "Press Cmd+K and the new Lyrics group finds songs the same way. Bible references like John 3:16 still go to the Bible.",
      "Small typos and half-finished words still find the song. Searching by title works exactly as before.",
      "Fixed: adding a Section header (or anything else) just after midnight could suddenly show an empty playlist. Nothing was deleted; the app was switching to a new day's service. It now keeps you on the service you are working on.",
      "If a newer service for today exists, you get a Switch to today's service button instead of being moved automatically.",
      "Clean up ad-hocs no longer deletes a service that still has items in it, or one that may be open right now.",
      "Fixed: when a song repeats its chorus and you add, delete or edit a slide while it is live, the next slide is now the one after the chorus on screen, not an earlier verse."
    ]
  },
  {
    "version": "0.1.405",
    "date": "2026-09-15",
    "headline": "Detection badges now show real numbers only",
    "highlights": [
      "Fixed: the red numbers on Bible detections, Songs and Cross-references now match exactly what you see when you open that panel.",
      "Fixed: when there is nothing detected, the number disappears instead of showing an old count.",
      "Pressing Clear on the AI chips bar now also clears those numbers back to zero. New detections still show up straight after.",
      "A Bible reference that does not exist (like John 99:99) no longer adds to the count.",
      "Fixed: after \"John 3:16\" then \"next verse\", the screen stays on verse 17 and no longer jumps back to 16.",
      "Fixed: polite commands like \"Amen church, can we go to next verse please\" now move to the next verse.",
      "Normal preaching such as \"we will see this in the next verse\" still does not move the screen.",
      "After Add slide, right-click the blank slide and choose Quick edit to type on it in the song's own font and colour, whatever theme or background is on.",
      "Cmd+Enter (Ctrl+Enter on Windows) saves. Send this slide live saves your text first, then puts it on screen.",
      "Pressing Esc or closing with unsaved typing now asks before throwing it away, and never clears what is on the projector."
    ]
  },
  {
    "version": "0.1.404",
    "date": "2026-09-14",
    "headline": "Signing in is more reliable — no more whole-church lockouts",
    "highlights": [
      "Fixed: if a password is typed wrong, the sign-in page now tells you clearly what happened and when you can try again, instead of a vague error.",
      "Fixed: several people signing in from the same church Wi-Fi no longer get locked out together because of one person's mistyped password."
    ]
  },
  {
    "version": "0.1.403",
    "date": "2026-09-14",
    "headline": "A full editor for your OBS live-stream words — with a real live preview",
    "highlights": [
      "Hardware → Screens → “Put lyrics on your live stream” is now a full editor for all three looks: Over your camera, Lower third, and Full projector look.",
      "The preview shows the slide that is ACTUALLY live right now, exactly as OBS will show it (or a sample song/verse when nothing is live).",
      "Over your camera (Full projector layout): text size, top/middle/bottom position, text colour, shadow or outline, and a dark background behind the words. Lower third: band style, height, position, text size, see-through, text colour and show/hide the verse reference. Full projector look: text size and darken background.",
      "Every tweak reaches OBS instantly while the app is open. Changing the LOOK itself only reaches links you create or copy from this new editor — links you already added to OBS keep their look, so nothing changes on your stream by surprise.",
      "Your own lower-third title (name / title lines) now shows on your OBS stream: in the band for the Lower third look, and on the Full projector look. On Over your camera it shows inside the band in the Lower third layout, or as a caption over the camera in the Full projector layout. It stays up until you send the next slide, or until you clear it.",
      "Your projector and operator screen are unchanged.",
      "Over your camera now has a Layout choice: Lower third (a see-through band over your camera — the default once you open the OBS editor on the computer running your service) or Full projector (the words across the whole camera picture, as before). In Lower third you can put the band Upper, Mid, Lower or a Custom position, and set its background, height, text size, see-through and text colour.",
      "In the camera Lower third layout, announcements, messages and timers are hidden so only the words sit over your camera. Switch the Layout to Full projector to show them."
    ]
  }
];
