// AUTO-GENERATED by scripts/build-changelog.mjs from changes/*.md — DO NOT EDIT.
// Add a changes/<slug>.md file instead (see changes/README.md).
import type { ChangelogEntry } from "./changelog-types";

export const GENERATED_CHANGELOG: ChangelogEntry[] = [
  {
    "version": "0.1.404",
    "date": "2026-09-14",
    "headline": "Signing in is more reliable — no more whole-church lockouts",
    "highlights": [
      "Fixed: if a password is typed wrong, the sign-in page now tells you clearly what happened and when you can try again, instead of a vague error.",
      "Fixed: several people signing in from the same church Wi-Fi no longer get locked out together because of one person's mistyped password."
    ]
  },
  {
    "version": "0.1.403",
    "date": "2026-09-14",
    "headline": "A full editor for your OBS live-stream words — with a real live preview",
    "highlights": [
      "Hardware → Screens → “Put lyrics on your live stream” is now a full editor for all three looks: Over your camera, Lower third, and Full projector look.",
      "The preview shows the slide that is ACTUALLY live right now, exactly as OBS will show it (or a sample song/verse when nothing is live).",
      "Over your camera (Full projector layout): text size, top/middle/bottom position, text colour, shadow or outline, and a dark background behind the words. Lower third: band style, height, position, text size, see-through, text colour and show/hide the verse reference. Full projector look: text size and darken background.",
      "Every tweak reaches OBS instantly while the app is open. Changing the LOOK itself only reaches links you create or copy from this new editor — links you already added to OBS keep their look, so nothing changes on your stream by surprise.",
      "Your own lower-third title (name / title lines) now shows on your OBS stream: in the band for the Lower third look, and on the Full projector look. On Over your camera it shows inside the band in the Lower third layout, or as a caption over the camera in the Full projector layout. It stays up until you send the next slide, or until you clear it.",
      "Your projector and operator screen are unchanged.",
      "Over your camera now has a Layout choice: Lower third (a see-through band over your camera — the default once you open the OBS editor on the computer running your service) or Full projector (the words across the whole camera picture, as before). In Lower third you can put the band Upper, Mid, Lower or a Custom position, and set its background, height, text size, see-through and text colour.",
      "In the camera Lower third layout, announcements, messages and timers are hidden so only the words sit over your camera. Switch the Layout to Full projector to show them."
    ]
  }
];
