#!/usr/bin/env python3
"""Build the self-hosted slide fonts (Fonts Phase 1, 2026-09-17).

Input : a checkout / download of github.com/google/fonts `ofl/<dir>/` folders
        (pass the path that contains `ofl/`).
Output: public/fonts/<id>/*.woff2 + OFL.txt, and src/app/slide-fonts.css.

Requires: pip install fonttools brotli   (dev-time only, NOT a repo dependency)
Usage   : python3 scripts/fonts/build-slide-fonts.py /path/to/google-fonts-checkout

Subset  : Basic Latin, Latin-1, Latin Extended-A/B, IPA bits, combining marks
          (U+0300-036F, Yoruba tone marks), Latin Extended Additional
          (U+1E00-1EFF: Yoruba ẹ ọ ṣ, Igbo ị ụ ṅ), punctuation + currency (₦).
          ONE file per face (no unicode-range split) so a verse never waits on a
          second late file mid-render.
Keep in sync with src/lib/fonts/registry.ts (test/fonts-files.test.ts enforces it).
"""
import io, os, sys, shutil
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
UNICODES = "U+0000-024F,U+0259,U+02B0-02FF,U+0300-036F,U+1E00-1EFF,U+2000-206F,U+20A0-20CF,U+2113,U+2122,U+2190-2193,U+2212,U+2215,U+FEFF,U+FFFD"

# id, family, google dir, faces: (style, source file, weight or (min,max), pinned axes)
VF = "variable"
FONTS = [
  ("sora", "Sora", "sora", [("normal", "Sora[wght].ttf", (100, 800), {})]),
  ("plus-jakarta-sans", "Plus Jakarta Sans", "plusjakartasans", [
    ("normal", "PlusJakartaSans[wght].ttf", (200, 800), {}),
    ("italic", "PlusJakartaSans-Italic[wght].ttf", (200, 800), {})]),
  ("inter", "Inter", "inter", [
    ("normal", "Inter[opsz,wght].ttf", (100, 900), {"opsz": 32}),
    ("italic", "Inter-Italic[opsz,wght].ttf", (100, 900), {"opsz": 32})]),
  ("playfair-display", "Playfair Display", "playfairdisplay", [
    ("normal", "PlayfairDisplay[wght].ttf", (400, 900), {}),
    ("italic", "PlayfairDisplay-Italic[wght].ttf", (400, 900), {})]),
  ("cormorant-garamond", "Cormorant Garamond", "cormorantgaramond", [
    ("normal", "CormorantGaramond[wght].ttf", (300, 700), {}),
    ("italic", "CormorantGaramond-Italic[wght].ttf", (300, 700), {})]),
  ("fraunces", "Fraunces", "fraunces", [
    ("normal", "Fraunces[SOFT,WONK,opsz,wght].ttf", (100, 900), {"SOFT": 0, "WONK": 1, "opsz": 144}),
    ("italic", "Fraunces-Italic[SOFT,WONK,opsz,wght].ttf", (100, 900), {"SOFT": 0, "WONK": 1, "opsz": 144})]),
  ("spectral", "Spectral", "spectral", [
    (st, f"Spectral-{nm}{'Italic' if st == 'italic' else ''}.ttf".replace("Regular" + "Italic", "Italic"), w, {})
    for (nm, w) in [("ExtraLight", 200), ("Light", 300), ("Regular", 400), ("Medium", 500), ("SemiBold", 600), ("Bold", 700), ("ExtraBold", 800)]
    for st in ("normal", "italic")]),
  ("montserrat", "Montserrat", "montserrat", [
    ("normal", "Montserrat[wght].ttf", (100, 900), {}),
    ("italic", "Montserrat-Italic[wght].ttf", (100, 900), {})]),
  ("dm-serif-display", "DM Serif Display", "dmserifdisplay", [
    ("normal", "DMSerifDisplay-Regular.ttf", 400, {}),
    ("italic", "DMSerifDisplay-Italic.ttf", 400, {})]),
]

def main(src):
  css = ["/* GENERATED by scripts/fonts/build-slide-fonts.py — do not edit by hand.",
         " * Self-hosted slide fonts (SIL OFL 1.1, see public/fonts/<id>/OFL.txt).",
         " * Plain @font-face with literal family names so stored theme/slide values",
         " * (\"Sora\", \"Montserrat\" …) resolve with no rename. No url() to any CDN:",
         " * works offline once cached. font-display: swap + AutoFitText refits. */", ""]
  for fid, family, gdir, faces in FONTS:
    out = os.path.join(ROOT, "public", "fonts", fid)
    shutil.rmtree(out, ignore_errors=True); os.makedirs(out)
    shutil.copy(os.path.join(src, "ofl", gdir, "OFL.txt"), os.path.join(out, "OFL.txt"))
    for style, fname, weight, pins in faces:
      font = TTFont(os.path.join(src, "ofl", gdir, fname))
      if "fvar" in font and pins:
        font = instancer.instantiateVariableFont(font, pins)
        buf = io.BytesIO(); font.save(buf); buf.seek(0); font = TTFont(buf)  # reload: subsetter trips on lazy gvar after instancing
      opts = subset.Options(); opts.flavor = "woff2"; opts.layout_features = ["*"]
      opts.name_IDs = ["*"]; opts.notdef_outline = True; opts.drop_tables += ["DSIG"]
      s = subset.Subsetter(opts); s.populate(unicodes=subset.parse_unicodes(UNICODES)); s.subset(font)
      wtag = f"{weight[0]}-{weight[1]}" if isinstance(weight, tuple) else str(weight)
      name = f"{fid}-{wtag}-{style}.woff2"
      font.flavor = "woff2"; font.save(os.path.join(out, name))
      wcss = f"{weight[0]} {weight[1]}" if isinstance(weight, tuple) else str(weight)
      css += ["@font-face {", f'  font-family: "{family}";', f"  font-style: {style};", f"  font-weight: {wcss};",
              "  font-display: swap;", f'  src: url("/fonts/{fid}/{name}") format("woff2");', "}"]
      print(name, os.path.getsize(os.path.join(out, name)))
  with open(os.path.join(ROOT, "src", "app", "slide-fonts.css"), "w") as fh:
    fh.write("\n".join(css) + "\n")

if __name__ == "__main__":
  main(sys.argv[1])
