// Slide font registry — the single source of truth for every font the operator
// can pick (Fonts Phase 1, 2026-09-17). Pure: no DOM, no server imports.
//
// Rules (never regress):
//  - Stored values are NEVER rewritten. resolveFont() only looks things up; an
//    unknown stored value stays exactly as it was (pickers show it as
//    "(current) <value>", renderers pass it through with a generic fallback).
//  - fontStack() is RENDER-TIME only. It must not be used to mutate stored data,
//    the wire payload, or slideOutputIdentity (content identity must stay stable
//    or the fade-pulse returns — CLAUDE.md rule 7, 2026-08-19).
//  - Bundled faces live in public/fonts/<id>/ and are declared in
//    src/app/slide-fonts.css (generated by scripts/fonts/build-slide-fonts.py).

export type FontCategory = "sans" | "serif" | "display" | "mono" | "system";
export type GenericFamily = "sans-serif" | "serif" | "monospace";

export type FontEntry = {
  /** Stable id (also the public/fonts/<id> folder for bundled fonts). */
  id: string;
  /** CSS family name, exactly as stored in themes/slides today. */
  family: string;
  label: string;
  category: FontCategory;
  /** Real weights this face has (bundled) or reliably renders (system). */
  weights: number[];
  italic: boolean;
  generic: GenericFamily;
  /** Extra CSS families appended before the generic (e.g. Helvetica → Arial). */
  fallbacks?: string[];
  /** Other stored spellings that mean this font (compared case-insensitively). */
  aliases?: string[];
  /** Glyph coverage checked with fontTools on the bundled files (system: unverified = false). */
  supports: { yoruba: boolean; igbo: boolean };
  /** true = bundled woff2 in public/fonts/<id>; false = relies on the OS. */
  bundled: boolean;
  /** Kept selectable for existing content; not a recommended pick. */
  legacy?: boolean;
};

const range = (lo: number, hi: number) => {
  const out: number[] = [];
  for (let w = lo; w <= hi; w += 100) out.push(w);
  return out;
};

export const FONT_REGISTRY: readonly FontEntry[] = [
  { id: "inter", family: "Inter", label: "Inter", category: "sans", weights: range(100, 900), italic: true, generic: "sans-serif", supports: { yoruba: true, igbo: true }, bundled: true },
  { id: "sora", family: "Sora", label: "Sora", category: "sans", weights: range(100, 800), italic: false, generic: "sans-serif", supports: { yoruba: false, igbo: false }, bundled: true },
  { id: "plus-jakarta-sans", family: "Plus Jakarta Sans", label: "Plus Jakarta Sans", category: "sans", weights: range(200, 800), italic: true, generic: "sans-serif", supports: { yoruba: true, igbo: true }, bundled: true },
  { id: "playfair-display", family: "Playfair Display", label: "Playfair Display", category: "serif", weights: range(400, 900), italic: true, generic: "serif", supports: { yoruba: false, igbo: false }, bundled: true },
  { id: "cormorant-garamond", family: "Cormorant Garamond", label: "Cormorant Garamond", category: "serif", weights: range(300, 700), italic: true, generic: "serif", supports: { yoruba: true, igbo: true }, bundled: true },
  { id: "fraunces", family: "Fraunces", label: "Fraunces", category: "serif", weights: range(100, 900), italic: true, generic: "serif", supports: { yoruba: true, igbo: false }, bundled: true },
  { id: "spectral", family: "Spectral", label: "Spectral", category: "serif", weights: range(200, 800), italic: true, generic: "serif", supports: { yoruba: true, igbo: true }, bundled: true },
  { id: "montserrat", family: "Montserrat", label: "Montserrat", category: "sans", weights: range(100, 900), italic: true, generic: "sans-serif", supports: { yoruba: true, igbo: true }, bundled: true },
  { id: "dm-serif-display", family: "DM Serif Display", label: "DM Serif Display", category: "display", weights: [400], italic: true, generic: "serif", supports: { yoruba: false, igbo: false }, bundled: true },
  // System fonts (not bundled — commercial faces we may not redistribute).
  { id: "georgia", family: "Georgia", label: "Georgia", category: "system", weights: [400, 700], italic: true, generic: "serif", supports: { yoruba: false, igbo: false }, bundled: false },
  { id: "helvetica", family: "Helvetica", label: "Helvetica", category: "system", weights: [400, 700], italic: true, generic: "sans-serif", fallbacks: ["Helvetica Neue", "Arial"], supports: { yoruba: false, igbo: false }, bundled: false },
  { id: "helvetica-neue", family: "Helvetica Neue", label: "Helvetica Neue", category: "system", weights: [400, 700], italic: true, generic: "sans-serif", fallbacks: ["Helvetica", "Arial"], supports: { yoruba: false, igbo: false }, bundled: false, legacy: true },
  { id: "arial", family: "Arial", label: "Arial", category: "system", weights: [400, 700], italic: true, generic: "sans-serif", supports: { yoruba: false, igbo: false }, bundled: false },
  { id: "times-new-roman", family: "Times New Roman", label: "Times New Roman", category: "system", weights: [400, 700], italic: true, generic: "serif", aliases: ["Times"], supports: { yoruba: false, igbo: false }, bundled: false },
  { id: "courier-new", family: "Courier New", label: "Courier New", category: "system", weights: [400, 700], italic: true, generic: "monospace", aliases: ["Courier"], supports: { yoruba: false, igbo: false }, bundled: false, legacy: true },
];

/** Kill switch: NEXT_PUBLIC_SLIDE_FONTS_V1="0" restores raw pass-through. Default ON. */
export function slideFontsV1Enabled(): boolean {
  try {
    return process.env.NEXT_PUBLIC_SLIDE_FONTS_V1 !== "0";
  } catch {
    return true;
  }
}

const GENERICS = new Set(["serif", "sans-serif", "monospace", "cursive", "fantasy", "system-ui", "ui-serif", "ui-sans-serif", "ui-monospace", "ui-rounded", "math", "emoji", "fangsong"]);
const LEGACY_SERIFS = new Set(["garamond", "palatino", "baskerville", "times"]);

const unquote = (s: string) => s.trim().replace(/^['"]|['"]$/g, "").trim();

/** First family of a CSS stack, unquoted. */
export function firstFamily(stored: string): string {
  return unquote(stored.split(",")[0] ?? "");
}

const byExact = new Map<string, FontEntry>();
const byLower = new Map<string, FontEntry>();
for (const e of FONT_REGISTRY) {
  byExact.set(e.family, e);
  byLower.set(e.family.toLowerCase(), e);
}
for (const e of FONT_REGISTRY) for (const a of e.aliases ?? []) if (!byLower.has(a.toLowerCase())) byLower.set(a.toLowerCase(), e);

/** exact → case-insensitive → alias → first family of a CSS stack. Unknown → undefined. */
export function resolveFont(stored: string | null | undefined): FontEntry | undefined {
  if (typeof stored !== "string") return undefined;
  const raw = stored.trim();
  if (!raw) return undefined;
  const hit = byExact.get(raw) ?? byLower.get(unquote(raw).toLowerCase());
  if (hit) return hit;
  if (raw.includes(",")) {
    const first = firstFamily(raw);
    return byExact.get(first) ?? byLower.get(first.toLowerCase());
  }
  return undefined;
}

// Multi-word names made of plain identifiers are valid unquoted CSS (and match the
// pre-registry wire strings byte-for-byte, e.g. "Times New Roman, serif").
const quoteFamily = (f: string) => (/^[a-zA-Z][a-zA-Z -]*$/.test(f) ? f : `"${f.replace(/"/g, "")}"`);

/**
 * Render-time CSS font-family that ALWAYS ends in a generic family, so a font
 * that is missing (Windows Helvetica, a failed download) degrades to the right
 * CLASS of face instead of the browser default serif (the 2026-08-11 "medieval
 * font" bug). Known fonts get their registry stack; unknown values keep their
 * raw text and gain a generic. Returns the raw value unchanged when the kill
 * switch is off. Never used to rewrite stored data.
 */
export function fontStack(stored: string | null | undefined): string | undefined {
  if (typeof stored !== "string") return undefined;
  const raw = stored.trim();
  if (!raw) return undefined;
  if (!slideFontsV1Enabled()) return stored;
  const parts = raw.split(",").map((p) => unquote(p)).filter(Boolean);
  const last = parts[parts.length - 1]?.toLowerCase() ?? "";
  if (parts.length > 1 && GENERICS.has(last)) return raw; // already a complete stack
  const entry = resolveFont(raw);
  if (entry && parts.length === 1) {
    return [entry.family, ...(entry.fallbacks ?? []), entry.generic].map((f) => (GENERICS.has(f) ? f : quoteFamily(f))).join(", ");
  }
  if (parts.length === 1 && GENERICS.has(last)) return raw; // bare generic ("serif")
  const generic: GenericFamily = entry?.generic ?? (LEGACY_SERIFS.has(firstFamily(raw).toLowerCase()) ? "serif" : "sans-serif");
  return `${raw}, ${generic}`;
}

export type FontPickerOption = { value: string; label: string; entry: FontEntry };

/** The one list every font picker renders (same order everywhere). */
export const FONT_PICKER_OPTIONS: readonly FontPickerOption[] = FONT_REGISTRY.map((e) => ({ value: e.family, label: e.label, entry: e }));

/**
 * Options for a <select> given the currently stored value. If the stored value
 * is not an option (unknown font, or a different spelling/stack), it is
 * prepended as "(current) <value>" so the picker shows the truth and never
 * silently overwrites it.
 */
export function pickerOptionsFor(current: string | null | undefined): { value: string; label: string }[] {
  const base = FONT_PICKER_OPTIONS.map((o) => ({ value: o.value, label: o.label }));
  if (typeof current !== "string" || !current || base.some((o) => o.value === current)) return base;
  return [{ value: current, label: `(current) ${current}` }, ...base];
}

/** The nearest real weight a font has (ties go to the heavier weight). Unknown font → requested weight. */
export function nearestWeight(stored: string | null | undefined, weight: number): number {
  const entry = resolveFont(stored);
  if (!entry || !entry.weights.length || !Number.isFinite(weight)) return weight;
  let best = entry.weights[0];
  for (const w of entry.weights) {
    if (Math.abs(w - weight) < Math.abs(best - weight) || (Math.abs(w - weight) === Math.abs(best - weight) && w > best)) best = w;
  }
  return best;
}

/** Weight options for a picker: the font's real weights, plus the stored weight if it isn't one. */
export function weightOptionsFor(stored: string | null | undefined, currentWeight?: number, fallback: number[] = [300, 400, 500, 600, 700, 800, 900]): number[] {
  const entry = resolveFont(stored);
  const list = entry ? [...entry.weights] : [...fallback];
  if (typeof currentWeight === "number" && Number.isFinite(currentWeight) && !list.includes(currentWeight)) list.push(currentWeight);
  return list.sort((a, b) => a - b);
}

/** A CSS font shorthand for document.fonts.load/check. */
export function fontLoadSpec(family: string, weight: number | string | undefined, italic: boolean, px = 48): string {
  const w = weight === undefined || weight === "" ? 400 : weight;
  return `${italic ? "italic " : ""}${w} ${px}px ${quoteFamily(firstFamily(family)) }`;
}
