-- Church defaults (2026-09-23, user-approved) — DEFAULT ANIMATED BACKGROUND.
-- Additive + idempotent. Safe to run repeatedly.
--
-- ============================================================================
-- ROLLBACK (written FIRST — run this to undo; nothing else depends on it):
--
--   ALTER TABLE church_preferences DROP COLUMN IF EXISTS default_background_id;
--
-- The app tolerates the column being ABSENT (before this migration or after
-- the rollback): the column is NOT on the main Drizzle `churchPreferences`
-- table object (whose db.select() lists every column on operate/operator/
-- settings/dashboard pages). It is read/written only with explicit raw SQL in
-- src/lib/server/church-defaults.ts, always inside a try/catch. A missing column therefore
-- means "no church default background" — it can NEVER make the operate page
-- fall back to KJV or fail to load.
-- ============================================================================
--
-- ============================================================================
-- DEPLOY RUNBOOK for branch feat/themes-songs-motion-0923 (strict order):
--   0. Record the current production deployment id (rollback =
--      `vercel promote <id>`).
--   1. Apply THIS migration (additive; safe before the code).
--   2. Style-lock backfill, BEFORE the code:
--        npx tsx scripts/backfill-style-lock.ts --dry-run --verbose
--      Check the per-church song/slide counts are NON-ZERO for churches that
--      have themed or hand-styled songs, then run it for real:
--        npx tsx scripts/backfill-style-lock.ts
--      Why before: the new renderer makes every UNLOCKED plain lyric slide
--      follow the church theme. Production today ignores `styleLocked`
--      (verified: origin/main src/lib/broadcast.ts isValidSlideObject has no
--      styleLocked check and accepts unknown keys; the renderer never reads
--      it), so writing it early changes nothing on screen.
--   3. Deploy the code (git → main → Vercel; preview first).
--   4. Re-run the backfill once after deploy (safe + idempotent; only
--      not-yet-locked objects are touched) to catch anything styled between
--      step 2 and step 3.
--   Rollback of step 2: `npx tsx scripts/backfill-style-lock.ts --rollback`
--      (removes styleLocked from exactly the objects the backfill locked).
-- ============================================================================
--
-- COLUMN ORDERING: either order is safe. Apply before the code for the feature
-- to be usable; before then the "Default animated background" picker just
-- won't save (the action returns a clear error).
--
-- Value: a built-in background template id (e.g. 'gentleWaves', 'holyFire') or
-- NULL = no default. Validated in the app against BUILT_IN_BACKGROUNDS; custom
-- uploads are per-machine localStorage and are not eligible.

ALTER TABLE church_preferences
  ADD COLUMN IF NOT EXISTS default_background_id text NULL;
